# Example of calling a URL
button1:
  type: api
  url: "http://example.com/api/foo"
  method: POST
  headers:
    Authorization: "bf5deadbeef8cc5efa6aa11"
    Content-Type: "application/json"
  body: '{"source": "onvis", "action": "foo"}'

# Run a local shell script
button2:
  type: shell
  command: "/opt/homebrew/bin/my_script.sh arg1"

button3:
  type: shell
  command: "say 'what is up smelly?'"

# Disable Pihole
button4:
  type: api
  url: "http://gpserver:7676/admin/api.php?disable=300&auth=z95x6e5c4a17d1ce58eb420a998d69dfd285e0e7c639706c715335d784e47f7dbff4cd7f6e"
  method: GET

button5:
  type: shell
  command: "osascript -e 'display notification \"Onvis 5 pressed\"'"
