button1:
  type: api
  url: "http://example.com/api/foo"
  method: POST
  headers:
    Authorization: "Bearer my-token"
    Content-Type: "application/json"
  body: '{"source": "onvis", "action": "foo"}'

button2:
  type: shell
  command: "/usr/local/bin/my_script.sh arg1"

button3:
  type: shell
  command: "say 'Button three was pressed'"

button4:
  type: api
  url: "http://gpserver:7676/admin/api.php?disable=300&auth=956e5417d1ce58eb420998d69dfd2850e7c639706715335d78447f7db4cd7f6e"
  method: GET

button5:
  type: shell
  command: "osascript -e 'display notification \"Onvis 5 pressed\"'"
