button1:
  type: api
  url: "http://example.com/api/foo"
  method: POST
  headers:
    Authorization: "bf58cc5efa6aa11"
    Content-Type: "application/json"
  body: '{"source": "onvis", "action": "foo"}'

button2:
  type: shell
  command: "/usr/local/bin/my_script.sh arg1"

button3:
  type: shell
  command: "say 'what is up smelly?'"

button4:
  type: api
  url: "http://SERVERNAME/admin/api.php?disable=300&auth=APIKEY"
  method: GET

button5:
  type: shell
  command: "osascript -e 'display notification \"Onvis 5 pressed\"'"
